In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,6]

In [3]:
type(l)

list

In [4]:
a = np.array(l)

In [5]:
type(a)

numpy.ndarray

In [6]:
a

array([1, 2, 3, 4, 6])

In [7]:
a1 = np.array([[1,2,3],[3,4,5]])

In [8]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [14]:
a2 = np.array([[[1,2,3],[2,3,5],[4,6,8]]])

In [15]:
a2

array([[[1, 2, 3],
        [2, 3, 5],
        [4, 6, 8]]])

In [16]:
a.ndim

1

In [17]:
a1.ndim

2

In [18]:
a2.ndim

3

In [19]:
l = [1,2,3,4]

In [25]:
a = np.asarray(l)

In [26]:
a

array([1, 2, 3, 4])

In [24]:
m = np.matrix(l)

In [27]:
m

matrix([[1, 2, 3, 4]])